name: Publish Docker Image

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php_version: ['7.4', '8.0', '8.1', '8.2', '8.3', '8.4']

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Log in to GitHub Container Registry
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push Docker image
      - name: Build and push Docker image
        run: |
          IMAGE=ghcr.io/${{ github.repository_owner }}/build:php-${{ matrix.php_version }}
          IMAGE=$(echo "$IMAGE" | tr '[:upper:]' '[:lower:]')
          docker build --build-arg PHP_VERSION=${{ matrix.php_version }} -t "$IMAGE" -f ./docker/Dockerfile .
          docker push "$IMAGE"
